### ISSUE TITLE
Error on server start-up

### ISSUE THREAD

**Issue by dylanvaughn** [metadatacenter/cedar-terminology-server#10]
Hi there - I'm setting up a new server instance and seeing this when I start this service:

```
[INFO] Launching Play! server
     [play] Play server process ID is 29502
     [play] [info] swagger - Plugin - starting initialisation
     [play] [info] swagger - Basepath configured as: https://terminology.metadatacenter.net
     [play] [info] swagger - Loading API metadata
     [play] [warn] swagger - ControllerScanner - looking for controllers with API annotation
     [play] [info] application - Initializing cache
     [play] [info] swagger - Found API controller:  controllers.TerminologyController
     [play] [info] application - Loading 'ontologies' cache
     [play] [info] application - Loading ontologies from BioPortal
     [play] [info] swagger - Plugin - initialization done
     [play] [info] play - Application started (Prod)
     [play] [info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9003
     [play] [warn] c.g.c.c.LocalCache - Exception thrown during refresh
     [play] java.util.concurrent.ExecutionException: javax.xml.ws.http.HTTPException
     [play]     at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476) [guava-19.0.jar:na]
     [play]     at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435) [guava-19.0.jar:na]
     [play]     at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79) [guava-19.0.jar:na]
     [play]     at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143) ~[guava-19.0.jar:na]
     [play]     at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2352) [guava-19.0.jar:na]
     [play] Caused by: javax.xml.ws.http.HTTPException: null
     [play]     at org.metadatacenter.terms.bioportal.dao.BpOntologyDAO.findAll(BpOntologyDAO.java:78) ~[cedar-terminology-server-core-0.1.0.jar:na]
     [play]     at org.metadatacenter.terms.bioportal.BioPortalService.findAllOntologies(BioPortalService.java:138) ~[cedar-terminology-server-core-0.1.0.jar:na]
     [play]     at org.metadatacenter.terms.TerminologyService.findAllOntologies(TerminologyService.java:41) ~[cedar-terminology-server-core-0.1.0.jar:na]
     [play]     at cache.Cache.getAllOntologiesAsMap(Cache.java:82) ~[classes/:na]
     [play]     at cache.Cache$2.load(Cache.java:58) ~[classes/:na]
```

Did I miss a step?

**Comment by egyedia** [comment]
Hi Dylan,

as a first step, please follow these instructions:

https://github.com/metadatacenter/cedar-docs/wiki/Build-and-launch-the-servers-on-OS-X

the key here is to modify this file: 

goterminology
vi conf/application-include-swagger.conf

and update the path to:

basepath="https://terminology.metadatacenter.orgx"

We are not sure that that is the cause, but that should definitely changed.

* Are you running several instances of this terminology server by accident? 
* I created a new environment on my laptop just yesterday evening, and the terminology server is working since then. I did several restarts.

Tell us what happens if you stop the server, make the changes, and start it again.

Attila

**Comment by martinjoconnor** [comment]
Just checking that this is still open?

**Comment by dylanvaughn** [comment]
this is resolved.
